// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://siindibbfajlgqhkzumw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpaW5kaWJiZmFqbGdxaGt6dW13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMTkyNDgsImV4cCI6MjA2NDc5NTI0OH0.A9dUQYWco1ZscOlBmgOr51_RUOMRB3-Ky3l9sYS0BxA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});